# Generated by Django 5.2.5 on 2025-09-11 10:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BugReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Korte beschrijving van de bug",
                        max_length=200,
                        verbose_name="Titel",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Gedetailleerde beschrijving van het probleem",
                        verbose_name="Beschrijving",
                    ),
                ),
                (
                    "steps_to_reproduce",
                    models.TextField(
                        blank=True,
                        help_text="Hoe kan de bug gereproduceerd worden?",
                        verbose_name="Stappen om te reproduceren",
                    ),
                ),
                (
                    "expected_behavior",
                    models.TextField(
                        blank=True,
                        help_text="Wat had er moeten gebeuren?",
                        verbose_name="Verwacht gedrag",
                    ),
                ),
                (
                    "actual_behavior",
                    models.TextField(
                        blank=True,
                        help_text="Wat gebeurde er daadwerkelijk?",
                        verbose_name="Werkelijk gedrag",
                    ),
                ),
                (
                    "browser_info",
                    models.CharField(
                        blank=True,
                        help_text="Welke browser en versie gebruikte je?",
                        max_length=200,
                        verbose_name="Browser informatie",
                    ),
                ),
                (
                    "reported_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Gerapporteerd op",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("in_progress", "In behandeling"),
                            ("resolved", "Opgelost"),
                            ("closed", "Gesloten"),
                        ],
                        default="open",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Laag"),
                            ("medium", "Gemiddeld"),
                            ("high", "Hoog"),
                            ("critical", "Kritiek"),
                        ],
                        default="medium",
                        max_length=20,
                        verbose_name="Prioriteit",
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(
                        blank=True,
                        help_text="Interne notities voor beheerders",
                        verbose_name="Beheerder notities",
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Opgelost op"
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_bug_reports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Toegewezen aan",
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bug_reports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Gerapporteerd door",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_bug_reports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Opgelost door",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bug Rapport",
                "verbose_name_plural": "Bug Rapporten",
                "ordering": ["-reported_at"],
            },
        ),
    ]
