# Generated by Django 5.2.5 on 2025-08-12 13:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0003_event_recurrence_end_date_event_recurrence_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AutomaticReminderLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reminder_type",
                    models.CharField(
                        choices=[
                            ("1_week", "1 week van tevoren"),
                            ("3_days", "3 dagen van tevoren"),
                            ("1_day", "1 dag van tevoren"),
                        ],
                        default="1_week",
                        max_length=20,
                        verbose_name="Type herinnering",
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Verzonden op"
                    ),
                ),
                (
                    "recipients_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Aantal ontvangers"
                    ),
                ),
                (
                    "success",
                    models.BooleanField(
                        default=True, verbose_name="Succesvol verzonden"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Foutmelding"),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="automatic_reminders",
                        to="events.event",
                        verbose_name="Evenement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Automatische herinnering",
                "verbose_name_plural": "Automatische herinneringen",
                "ordering": ["-sent_at"],
                "unique_together": {("event", "reminder_type")},
            },
        ),
    ]
