# Generated by Django 5.2.5 on 2025-08-14 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_matchstatistic"),
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduleConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Unieke naam voor deze taak configuratie",
                        max_length=100,
                        unique=True,
                        verbose_name="Configuratie naam",
                    ),
                ),
                (
                    "task",
                    models.CharField(
                        choices=[
                            (
                                "notifications.tasks.send_automatic_event_reminders",
                                "Automatische evenement herinneringen",
                            ),
                            (
                                "notifications.tasks.cleanup_old_reminder_logs",
                                "Opruimen oude herinnering logs",
                            ),
                        ],
                        help_text="Welke taak moet uitgevoerd worden",
                        max_length=200,
                        verbose_name="Taak",
                    ),
                ),
                (
                    "reminder_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1_week", "1 week van tevoren"),
                            ("3_days", "3 dagen van tevoren"),
                            ("1_day", "1 dag van tevoren"),
                        ],
                        help_text="Voor reminder taken, welk type herinnering",
                        max_length=20,
                        verbose_name="Type herinnering",
                    ),
                ),
                (
                    "minute",
                    models.CharField(
                        default="0",
                        help_text="Minuut (0-59, *, */5, etc.)",
                        max_length=100,
                        verbose_name="Minuut",
                    ),
                ),
                (
                    "hour",
                    models.CharField(
                        default="9",
                        help_text="Uur (0-23, *, */2, etc.)",
                        max_length=100,
                        verbose_name="Uur",
                    ),
                ),
                (
                    "day_of_week",
                    models.CharField(
                        default="*",
                        help_text="Dag van de week (0=Zondag, 1=Maandag, *, etc.)",
                        max_length=100,
                        verbose_name="Dag van de week",
                    ),
                ),
                (
                    "day_of_month",
                    models.CharField(
                        default="*",
                        help_text="Dag van de maand (1-31, *, */2, etc.)",
                        max_length=100,
                        verbose_name="Dag van de maand",
                    ),
                ),
                (
                    "month_of_year",
                    models.CharField(
                        default="*",
                        help_text="Maand van het jaar (1-12, *, etc.)",
                        max_length=100,
                        verbose_name="Maand van het jaar",
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Of deze taak actief is",
                        verbose_name="Actief",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Taak configuratie",
                "verbose_name_plural": "Taak configuraties",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="EventScheduleOverride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "override_minute",
                    models.CharField(
                        blank=True,
                        help_text="Laat leeg om basis configuratie te gebruiken",
                        max_length=100,
                        verbose_name="Override minuut",
                    ),
                ),
                (
                    "override_hour",
                    models.CharField(
                        blank=True,
                        help_text="Laat leeg om basis configuratie te gebruiken",
                        max_length=100,
                        verbose_name="Override uur",
                    ),
                ),
                (
                    "override_day_of_week",
                    models.CharField(
                        blank=True,
                        help_text="Laat leeg om basis configuratie te gebruiken",
                        max_length=100,
                        verbose_name="Override dag van de week",
                    ),
                ),
                (
                    "override_day_of_month",
                    models.CharField(
                        blank=True,
                        help_text="Laat leeg om basis configuratie te gebruiken",
                        max_length=100,
                        verbose_name="Override dag van de maand",
                    ),
                ),
                (
                    "override_month_of_year",
                    models.CharField(
                        blank=True,
                        help_text="Laat leeg om basis configuratie te gebruiken",
                        max_length=100,
                        verbose_name="Override maand van het jaar",
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Of deze override actief is",
                        verbose_name="Actief",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_override",
                        to="events.event",
                        verbose_name="Evenement",
                    ),
                ),
                (
                    "configuration",
                    models.ForeignKey(
                        help_text="De basis configuratie waarop deze override gebaseerd is",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="notifications.scheduleconfiguration",
                        verbose_name="Basis configuratie",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evenement taak override",
                "verbose_name_plural": "Evenement taak overrides",
                "ordering": ["event__date"],
            },
        ),
    ]
