# Generated by Django 5.2.5 on 2025-08-15 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_scheduleconfiguration_eventscheduleoverride"),
    ]

    operations = [
        migrations.AlterField(
            model_name="automaticreminderlog",
            name="reminder_type",
            field=models.CharField(
                choices=[
                    ("1_week", "1 week van tevoren"),
                    ("3_days", "3 dagen van tevoren"),
                    ("1_day", "1 dag van tevoren"),
                    ("morning_of", "Dag van het evenement"),
                ],
                default="1_week",
                max_length=20,
                verbose_name="Type herinnering",
            ),
        ),
        migrations.AlterField(
            model_name="scheduleconfiguration",
            name="task",
            field=models.CharField(
                choices=[
                    (
                        "notifications.tasks.send_automatic_event_reminders",
                        "Automatische evenement herinneringen",
                    ),
                    (
                        "notifications.tasks.cleanup_old_reminder_logs",
                        "Opruimen oude herinnering logs",
                    ),
                    (
                        "notifications.tasks.send_event_summary_to_attendees",
                        "Ochtend van het evenement notificaties",
                    ),
                ],
                help_text="Welke taak moet uitgevoerd worden",
                max_length=200,
                verbose_name="Taak",
            ),
        ),
    ]
