# Generated by Django 5.2.5 on 2025-08-15 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_alter_automaticreminderlog_reminder_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scheduleconfiguration",
            name="task",
            field=models.CharField(
                choices=[
                    (
                        "notifications.tasks.send_automatic_event_reminders",
                        "Automatische evenement herinneringen",
                    ),
                    (
                        "notifications.tasks.cleanup_old_reminder_logs",
                        "Opruimen oude herinnering logs",
                    ),
                    (
                        "notifications.tasks.send_event_summary_to_attendees",
                        "Notificatie evenement voor aanwezigen",
                    ),
                ],
                help_text="Welke taak moet uitgevoerd worden",
                max_length=200,
                verbose_name="Taak",
            ),
        ),
    ]
