# Generated by Django 5.2.5 on 2025-08-15 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0004_alter_scheduleconfiguration_task"),
    ]

    operations = [
        migrations.AlterField(
            model_name="automaticreminderlog",
            name="reminder_type",
            field=models.CharField(
                choices=[
                    ("1_week", "1 week van tevoren"),
                    ("3_days", "3 dagen van tevoren"),
                    ("1_day", "1 dag van tevoren"),
                    ("morning_of", "Ochtend van het evenement"),
                ],
                default="1_week",
                max_length=20,
                verbose_name="Type herinnering",
            ),
        ),
        migrations.AlterField(
            model_name="scheduleconfiguration",
            name="reminder_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1_week", "1 week van tevoren"),
                    ("3_days", "3 dagen van tevoren"),
                    ("1_day", "1 dag van tevoren"),
                    ("morning_of", "Dag van het evenement"),
                ],
                help_text="Voor reminder taken, welk type herinnering",
                max_length=20,
                verbose_name="Type herinnering",
            ),
        ),
    ]
