# Generated by Django 5.2.5 on 2025-08-21 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0005_alter_automaticreminderlog_reminder_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="automaticreminderlog",
            name="reminder_type",
            field=models.CharField(
                choices=[
                    ("1_week", "1 week van tevoren"),
                    ("3_days", "3 dagen van tevoren"),
                    ("1_day", "1 dag van tevoren"),
                    ("morning_of", "Dag van het evenement"),
                ],
                default="1_week",
                max_length=20,
                verbose_name="Type herinnering",
            ),
        ),
        migrations.CreateModel(
            name="PushSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "endpoint",
                    models.URLField(
                        help_text="Push service endpoint URL",
                        max_length=500,
                        verbose_name="Endpoint",
                    ),
                ),
                (
                    "p256dh_key",
                    models.TextField(
                        help_text="Public key for encryption", verbose_name="P256DH Key"
                    ),
                ),
                (
                    "auth_key",
                    models.TextField(
                        help_text="Authentication secret", verbose_name="Auth Key"
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True,
                        help_text="Browser/device information",
                        verbose_name="User Agent",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_used", models.DateTimeField(auto_now=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Of deze subscription actief is",
                        verbose_name="Actief",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="push_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Gebruiker",
                    ),
                ),
            ],
            options={
                "verbose_name": "Push Subscription",
                "verbose_name_plural": "Push Subscriptions",
                "ordering": ["-created_at"],
                "unique_together": {("user", "endpoint")},
            },
        ),
        migrations.CreateModel(
            name="PushNotificationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Titel")),
                ("body", models.TextField(verbose_name="Bericht")),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        help_text="URL to open when notification is clicked",
                        verbose_name="URL",
                    ),
                ),
                (
                    "icon",
                    models.CharField(blank=True, max_length=200, verbose_name="Icoon"),
                ),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "success",
                    models.BooleanField(default=False, verbose_name="Succesvol"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Foutmelding"),
                ),
                (
                    "response_code",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Response Code"
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_logs",
                        to="notifications.pushsubscription",
                        verbose_name="Subscription",
                    ),
                ),
            ],
            options={
                "verbose_name": "Push Notification Log",
                "verbose_name_plural": "Push Notification Logs",
                "ordering": ["-sent_at"],
            },
        ),
    ]
