repos:
  - repo: local
    hooks:
      # Prevent manual requirements.txt files
      - id: prevent-manual-requirements-edits
        name: Prevent manual changes to requirements.txt
        entry: scripts/hooks/check-requirements.sh
        language: script
        types: [text]

      # Strip notebook outputs
      - id: nbstripout-autoadd
        name: nbstripout (auto-add notebooks)
        entry: scripts/hooks/nbstripout-autoadd.sh
        language: python
        types: [jupyter]
        additional_dependencies: [nbstripout]

      # Auto-format Python code with Black
      - id: black-autoformat
        name: Auto-format Python with Black
        entry: scripts/hooks/black-autoformat.sh
        language: python
        additional_dependencies: [black]
        types: [python]

  # Dependency vulnerability scanning
  - repo: https://github.com/pypa/pip-audit
    rev: v2.9.0
    hooks:
      - id: pip-audit
        args: ['--progress-spinner', 'off']
        stages: [pre-commit]

  # # Secrets scanning
  # - repo: https://github.com/Yelp/detect-secrets
  #   rev: v1.5.0
  #   hooks:
  #     - id: detect-secrets
  #       args: ['--baseline', '.secrets.baseline']
  #       exclude: ^tests/

  # Notebook/text sync
  - repo: https://github.com/mwouts/jupytext
    rev: v1.17.2
    hooks:
      - id: jupytext
        args: [--sync]
        require_serial: true

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.7
    hooks:
      - id: ruff
        name: Ruff (linting + extra isort + rules)
        args: [--fix]
        types: [python]
  
  # - repo: local
  #   hooks:
  #     - id: pytest
  #       name: Run pytest with coverage & beartype
  #       entry: pytest --cov --cov-fail-under=80 --beartype-packages=utils,example
  #       language: python
  #       additional_dependencies:
  #         - pytest
  #         - pytest-cov
  #         - pytest-beartype
  #       pass_filenames: false
  #       always_run: true
  #       stages: [pre-commit]

  # - repo: local
  #   hooks:
  #     - id: pytest
  #       name: Run pytest with coverage & beartype
  #       entry: bash scripts/hooks/precommit_pytest.sh
  #       language: system
  #       pass_filenames: false
  #       always_run: true
  #       stages: [pre-commit]


