# Generated by Django 5.2.5 on 2025-08-19 21:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Poll",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Titel van de poll",
                        max_length=200,
                        verbose_name="Titel",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optionele beschrijving van de poll",
                        verbose_name="Beschrijving",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Aangemaakt op"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Actieve polls zijn zichtbaar en kunnen votes ontvangen",
                        verbose_name="Actief",
                    ),
                ),
                (
                    "allow_multiple_choices",
                    models.BooleanField(
                        default=False,
                        help_text="Kunnen spelers meerdere opties selecteren?",
                        verbose_name="Meerdere antwoorden toestaan",
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Optionele einddatum waarop de poll automatisch sluit",
                        null=True,
                        verbose_name="Einddatum",
                    ),
                ),
                (
                    "closed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Gesloten op"
                    ),
                ),
                (
                    "closed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="closed_polls",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Gesloten door",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_polls",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Aangemaakt door",
                    ),
                ),
            ],
            options={
                "verbose_name": "Poll",
                "verbose_name_plural": "Polls",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PollOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=200, verbose_name="Optie tekst")),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Volgorde waarin de optie wordt getoond",
                        verbose_name="Volgorde",
                    ),
                ),
                (
                    "poll",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="polls.poll",
                        verbose_name="Poll",
                    ),
                ),
            ],
            options={
                "verbose_name": "Poll Optie",
                "verbose_name_plural": "Poll Opties",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "voted_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Gestemd op"
                    ),
                ),
                (
                    "poll_option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="polls.polloption",
                        verbose_name="Poll optie",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="poll_votes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Gebruiker",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stem",
                "verbose_name_plural": "Stemmen",
                "unique_together": {("user", "poll_option")},
            },
        ),
    ]
