services:
  db:
    image: postgres:17
    restart: always
    env_file:
      - .env.prod
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - rap_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 1g
        reservations:
          memory: 512m

  redis:
    image: redis:7
    restart: always
    networks:
      - rap_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 128m
        reservations:
          memory: 64m

  web:
    image: ${IMAGE_REGISTRY}/${IMAGE_REPOSITORY}:${IMAGE_TAG}
    restart: always
    env_file:
      - .env.prod
    secrets:
      - vapid_private_key
      - vapid_public_key
    environment:
      VAPID_PRIVATE_KEY_FILE: /run/secrets/vapid_private_key
      VAPID_PUBLIC_KEY_PEM_FILE: /run/secrets/vapid_public_key
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    networks:
      - rap_network
    expose:
      - "8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "python - <<'PY'\nimport socket,sys\ns=socket.socket(); s.settimeout(3)\ntry:\n  s.connect(('localhost',8000)); s.close(); sys.exit(0)\nexcept Exception:\n  sys.exit(1)\nPY"
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 15s
    deploy:
      resources:
        limits:
          memory: 1g
        reservations:
          memory: 512m

  celery_worker:
    image: ${IMAGE_REGISTRY}/${IMAGE_REPOSITORY}:${IMAGE_TAG}
    restart: always
    env_file:
      - .env.prod
    secrets:
      - vapid_private_key
      - vapid_public_key
    environment:
      VAPID_PRIVATE_KEY_FILE: /run/secrets/vapid_private_key
      VAPID_PUBLIC_KEY_PEM_FILE: /run/secrets/vapid_public_key
    networks:
      - rap_network
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: celery -A rap_web worker --loglevel=info --concurrency=2
    deploy:
      resources:
        limits:
          memory: 512m
        reservations:
          memory: 256m

  celery_beat:
    image: ${IMAGE_REGISTRY}/${IMAGE_REPOSITORY}:${IMAGE_TAG}
    restart: always
    env_file:
      - .env.prod
    secrets:
      - vapid_private_key
      - vapid_public_key
    environment:
      VAPID_PRIVATE_KEY_FILE: /run/secrets/vapid_private_key
      VAPID_PUBLIC_KEY_PEM_FILE: /run/secrets/vapid_public_key
    networks:
      - rap_network
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: celery -A rap_web beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    deploy:
      resources:
        limits:
          memory: 256m
        reservations:
          memory: 128m

  nginx:
    image: nginx:stable
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/error-pages:/etc/nginx/error-pages:ro
      - static_volume:/app/staticfiles:ro
      - media_volume:/app/media:ro
      - /etc/letsencrypt/live/rap8.nl/fullchain.pem:/etc/nginx/ssl/fullchain.pem:ro
      - /etc/letsencrypt/live/rap8.nl/privkey.pem:/etc/nginx/ssl/privkey.pem:ro
    networks:
      - rap_network
    depends_on:
      web:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 512m
        reservations:
          memory: 128m

volumes:
  postgres_data:
  static_volume:
  media_volume:

secrets:
  vapid_private_key:
    file: ./vapid_private_key
  vapid_public_key:
    file: ./vapid_public_key

networks:
  rap_network:
    name: rap_network
    driver: bridge
