# Generated by Django 5.2.5 on 2025-08-08 09:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvitationCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unieke code die gebruikers kunnen gebruiken om te registreren",
                        max_length=50,
                        unique=True,
                        verbose_name="Uitnodigingscode",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Beschrijving van waarvoor deze code is (bijv. 'Nieuwe spelers 2025')",
                        max_length=255,
                        verbose_name="Beschrijving",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Alleen actieve codes kunnen gebruikt worden voor registratie",
                        verbose_name="Actief",
                    ),
                ),
                (
                    "max_uses",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Laat leeg voor onbeperkt gebruik",
                        null=True,
                        verbose_name="Maximaal aantal gebruiken",
                    ),
                ),
                (
                    "used_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Aantal keer gebruikt"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Aangemaakt op"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Laat leeg als de code niet verloopt",
                        null=True,
                        verbose_name="Verloopt op",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Aangemaakt door",
                    ),
                ),
            ],
            options={
                "verbose_name": "Uitnodigingscode",
                "verbose_name_plural": "Uitnodigingscodes",
                "ordering": ["-created_at"],
            },
        ),
    ]
