# Generated by Django 5.2.5 on 2025-08-08 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_invitationcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="huisnummer",
            field=models.CharField(
                blank=True, max_length=10, verbose_name="Huisnummer"
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="plaats",
            field=models.CharField(blank=True, max_length=50, verbose_name="Plaats"),
        ),
        migrations.AddField(
            model_name="player",
            name="postcode",
            field=models.CharField(blank=True, max_length=10, verbose_name="Postcode"),
        ),
        migrations.AddField(
            model_name="player",
            name="straat",
            field=models.CharField(blank=True, max_length=100, verbose_name="Straat"),
        ),
        migrations.AddField(
            model_name="player",
            name="toevoeging",
            field=models.CharField(
                blank=True, max_length=10, verbose_name="Toevoeging"
            ),
        ),
    ]
