# Generated by Django 5.2.5 on 2025-08-08 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_add_address_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="foto",
            field=models.ImageField(
                blank=True,
                default="media/sv-rap.png",
                null=True,
                upload_to="profile_pics/",
                verbose_name="Profielfoto",
            ),
        ),
    ]
