# Generated by Django 5.2.5 on 2025-08-12 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_player_foto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="foto",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="profile_pics/",
                verbose_name="Profielfoto",
            ),
        ),
    ]
