# Generated by Django 5.2.5 on 2025-09-12 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_player_foto"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitationcode",
            name="user_type",
            field=models.CharField(
                choices=[("player", "Speler"), ("invaller", "Invaller")],
                default="player",
                help_text="Type gebruiker dat met deze code geregistreerd wordt",
                max_length=20,
                verbose_name="Gebruikerstype",
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="user_type",
            field=models.CharField(
                choices=[("player", "Speler"), ("invaller", "Invaller")],
                default="player",
                help_text="Type gebruiker: speler (volledige toegang) of invaller (alleen wedstrijden)",
                max_length=20,
                verbose_name="Gebruikerstype",
            ),
        ),
    ]
