# Generated by Django 5.2.5 on 2025-08-07 15:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={
                "ordering": ["date"],
                "verbose_name": "Evenement",
                "verbose_name_plural": "Evenementen",
            },
        ),
        migrations.AddField(
            model_name="event",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="event",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("training", "Training"),
                    ("wedstrijd", "Wedstrijd"),
                    ("uitje", "Teamuitje"),
                    ("vergadering", "Vergadering"),
                    ("overig", "Overig"),
                ],
                default="training",
                max_length=20,
                verbose_name="Type evenement",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="is_mandatory",
            field=models.BooleanField(
                default=False,
                help_text="Aanwezigheid is verplicht voor alle spelers",
                verbose_name="Verplichte aanwezigheid",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="max_participants",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Laat leeg voor onbeperkt",
                null=True,
                verbose_name="Maximaal aantal deelnemers",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="date",
            field=models.DateTimeField(verbose_name="Datum en tijd"),
        ),
        migrations.AlterField(
            model_name="event",
            name="description",
            field=models.TextField(blank=True, verbose_name="Beschrijving"),
        ),
        migrations.AlterField(
            model_name="event",
            name="location",
            field=models.CharField(blank=True, max_length=255, verbose_name="Locatie"),
        ),
        migrations.AlterField(
            model_name="event",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Naam"),
        ),
    ]
