# Generated by Django 5.2.5 on 2025-08-08 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_alter_event_options_event_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="recurrence_end_date",
            field=models.DateField(
                blank=True,
                help_text="Laatste datum waarop het evenement herhaald wordt",
                null=True,
                verbose_name="Einddatum herhaling",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="recurrence_type",
            field=models.CharField(
                choices=[
                    ("none", "Geen herhaling"),
                    ("daily", "Dagelijks"),
                    ("weekly", "Wekelijks"),
                    ("biweekly", "Tweewekelijks"),
                    ("monthly", "Maandelijks"),
                    ("yearly", "Jaarlijks"),
                ],
                default="none",
                help_text="Hoe vaak het evenement herhaald wordt",
                max_length=20,
                verbose_name="Herhalingstype",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="recurring_event_link_id",
            field=models.UUIDField(
                blank=True,
                help_text="Unieke ID die alle herhalende evenementen met elkaar verbindt",
                null=True,
                verbose_name="Herhalingsgroep ID",
            ),
        ),
    ]
