# Generated by Django 5.2.5 on 2025-08-13 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_recurrence_end_date_event_recurrence_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statistic_type', models.CharField(choices=[('goal', 'Doelpunt'), ('assist', 'Assist'), ('yellow_card', 'Gele kaart'), ('red_card', 'Rode kaart'), ('substitution_in', 'Wissel in'), ('substitution_out', 'Wissel uit'), ('penalty_scored', 'Penalty gescoord'), ('penalty_missed', 'Penalty gemist'), ('own_goal', 'Eigen doelpunt'), ('clean_sheet', 'Clean sheet'), ('saves', 'Reddingen'), ('man_of_the_match', 'Man van de wedstrijd')], max_length=20, verbose_name='Type statistiek')),
                ('value', models.IntegerField(default=1, help_text='Aantal voor deze statistiek (bijv. aantal doelpunten, aantal kaarten)', verbose_name='Waarde')),
                ('minute', models.PositiveIntegerField(blank=True, help_text='In welke minuut van de wedstrijd (optioneel)', null=True, verbose_name='Minuut')),
                ('notes', models.TextField(blank=True, help_text='Extra informatie over deze statistiek', verbose_name='Opmerkingen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_statistics', to=settings.AUTH_USER_MODEL, verbose_name='Toegevoegd door')),
                ('event', models.ForeignKey(help_text='Het evenement waaraan deze statistiek is gekoppeld', on_delete=django.db.models.deletion.CASCADE, to='events.event', verbose_name='Evenement')),
                ('player', models.ForeignKey(help_text='De speler aan wie deze statistiek toebehoort', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Speler')),
            ],
            options={
                'verbose_name': 'Wedstrijd Statistiek',
                'verbose_name_plural': 'Wedstrijd Statistieken',
                'ordering': ['event', 'minute', 'statistic_type'],
                'unique_together': {('event', 'player', 'statistic_type', 'minute')},
            },
        ),
    ]
