#!/bin/bash
if git diff --cached --name-only | grep -q "^requirements.txt$"; then
  if ! grep -q "# This file is autogenerated by pip-compile" requirements.txt; then
    echo "❌ ERROR: requirements.txt appears to have been modified manually."
    echo "Use 'pip-compile' instead. See 2.2 in the docs."
    exit 1
  fi
fi

if git diff --cached --name-only | grep -q "^requirements-dev.txt$"; then
  if ! grep -q "# This file is autogenerated by pip-compile" requirements-dev.txt; then
    echo "❌ ERROR: requirements-dev.txt appears to have been modified manually."
    echo "Use 'pip-compile' instead. See 2.2 in the docs."
    exit 1
  fi
fi